#!/bin/bash
# ============================================
# Star Flow — Audio Export Script
# Generated by Audio Prep Tool
# ============================================

set -e

# --- Configuration ---
INPUT_DIR="${INPUT_DIR:-.}"
OUTPUT_DIR="${OUTPUT_DIR:-./output}"
SFX_QUALITY=3
MUSIC_QUALITY=5

mkdir -p "$OUTPUT_DIR/sfx" "$OUTPUT_DIR/music"

# --- From: UI Click - SFX.mp3 ---
ffmpeg -y \
  -i "$INPUT_DIR/UI Click - SFX.mp3" \
  -ss 3.7107 \
  -t 1.0549 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/menu_open.ogg"

ffmpeg -y \
  -i "$INPUT_DIR/UI Click - SFX.mp3" \
  -ss 5.7479 \
  -t 1.0550 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/planet_select.ogg"

ffmpeg -y \
  -i "$INPUT_DIR/UI Click - SFX.mp3" \
  -ss 12.8054 \
  -t 0.9822 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/route_create.ogg"

ffmpeg -y \
  -i "$INPUT_DIR/UI Click - SFX.mp3" \
  -ss 11.9323 \
  -t 0.7276 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/planet_capture.ogg"

ffmpeg -y \
  -i "$INPUT_DIR/UI Click - SFX.mp3" \
  -ss 0.8367 \
  -t 0.5457 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/ui_click.ogg"

ffmpeg -y \
  -i "$INPUT_DIR/UI Click - SFX.mp3" \
  -ss 2.9103 \
  -t 0.8004 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/route_disconnect.ogg"

# --- From: Battle Intense - Star Flow Command.mp3 ---
ffmpeg -y \
  -i "$INPUT_DIR/Battle Intense - Star Flow Command.mp3" \
  -ss 94.9085 \
  -t 0.4515 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/explosion.ogg"

ffmpeg -y \
  -i "$INPUT_DIR/Battle Intense - Star Flow Command.mp3" \
  -ss 80.5497 \
  -t 1.1401 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/defeat.ogg"

ffmpeg -y \
  -i "$INPUT_DIR/Battle Intense - Star Flow Command.mp3" \
  -ss 10.0011 \
  -t 17.2386 \
  -ac 2 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 5 \
  "$OUTPUT_DIR/music/battle_intense.ogg"

# --- From: Explosion - SFX.mp3 ---
ffmpeg -y \
  -i "$INPUT_DIR/Explosion - SFX.mp3" \
  -ss 63.4694 \
  -t 2.3132 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/star_danger.ogg"

ffmpeg -y \
  -i "$INPUT_DIR/Explosion - SFX.mp3" \
  -ss 66.3358 \
  -t 1.8103 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/gravity_well.ogg"

ffmpeg -y \
  -i "$INPUT_DIR/Explosion - SFX.mp3" \
  -ss 19.1832 \
  -t 20.9096 \
  -ac 2 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 5 \
  "$OUTPUT_DIR/music/menu_theme.ogg"

ffmpeg -y \
  -i "$INPUT_DIR/Explosion - SFX.mp3" \
  -ss 56.3985 \
  -t 5.5631 \
  -ac 1 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 3 \
  "$OUTPUT_DIR/sfx/victory.ogg"

# --- From: Orbit Drift.mp3 ---
ffmpeg -y \
  -i "$INPUT_DIR/Orbit Drift.mp3" \
  -ss 21.5755 \
  -t 65.6070 \
  -ac 2 \
  -ar 44100 \
  -c:a libvorbis \
  -q:a 5 \
  "$OUTPUT_DIR/music/ambient_space.ogg"

# --- Summary ---
echo "Export complete! Files in $OUTPUT_DIR:"
find "$OUTPUT_DIR" -name "*.ogg" -exec ls -lh {} \;
